import React from "react";
import Head from "next/head";
import PostsList from "@/components/posts/PostsList";
import Search from "@/components/search/Search";
import usePostsFetch from "@/components/hooks/usePostsFetch";

type PostsProps = {
  posts: PostProps[];
};

export interface PostProps {
  id: number;
  title: string;
  body: string;
  tags: string[];
  reaction: number;
}

const Posts = ({ posts }: PostsProps) => {
  const { keyword, setKeyWord, postsResults } = usePostsFetch({ posts });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search keyword={keyword} setKeyWord={setKeyWord} />
      <PostsList results={postsResults} />
    </>
  );
};

export default Posts;

export async function getServerSideProps() {
  const res = await fetch("https://dummyjson.com/posts");
  const { posts } = await res.json();
  return {
    props: {
      posts,
    },
  };
}
