import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ProductsLists from "@/components/products/ProductsLists";
import Search from "@/components/search/Search";
import useProductsFetch from "../components/hooks/useProductFetch";
import Nav from "@/components/Nav";
import Container from "@/layouts/Container";

export interface ProductProps {
  id: number;
  title: string;
  description: string;
  price: number;
}

interface ProductsProps {
  products: ProductProps[];
}

export default function Product({ products }: ProductsProps) {
  const { keyword, results, setKeyWord } = useProductsFetch({ products });
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search keyword={keyword} setKeyWord={setKeyWord} />
      <ProductsLists results={results} />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://dummyjson.com/products");
  const { products } = await res.json();

  return {
    props: {
      products,
    },
  };
}
